version: 2
updates:

  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gitsubmodule"
    directory: "external/common_items"
    schedule:
      interval: "daily"

  - package-ecosystem: "gitsubmodule"
    directory: "external/fmt"
    schedule:
      interval: "daily"

  - package-ecosystem: "gitsubmodule"
    directory: "external/bitmap"
    schedule:
      interval: "daily"

  - package-ecosystem: "gitsubmodule"
    directory: "external/Fronter"
    schedule:
      interval: "daily"
